UIX-15: Added basic API wrapper
bjorn-uix/uix-web-platform pull request #17
Opened 2022-09-01 20:25 UTC by psy-tama

**------ For PR creator ------**

UIX-15: Added basic API wrapper

## Creator Checklist

- [ ] Self review
- [ ] If this is a bug, add small root cause and fix
- [ ] If UI change, attach screenshot or recording

**-------- For Reviewer ------**

## Reviewer Checklist

- [ ] JIRA is linked correctly
- [ ] Base branch is main

2022-09-01 20:28 UTC, psy-tama commented
@bjorn-uix @takashi-uix Added a basic version of API wrapper with useSWR, types are not used properly as it s not configured completely.

2022-09-02 20:56 UTC, psy-tama commented
This is now fully typed and functional.

2022-09-03 07:35 UTC, takashi-uix requested changes

2022-09-03 07:35 UTC, takashi-uix commented on src/hooks/useFetch/useFetch.ts
> +    const res = await fetch(url, options);
How will we inject token if required..?

2022-09-03 07:35 UTC, takashi-uix commented on src/hooks/useFetch/helper.ts
> +      body: JSON.stringify(requestBody)
any other way to do this?

2022-09-03 07:35 UTC, takashi-uix commented on src/hooks/useFetch/useFetch.ts
> +    () => (enabled ? [url, sanitizedOptions] : null),
if not enabled nothing will happen i see no logic when enabled === false ?

2022-09-03 07:38 UTC, psy-tama commented on src/hooks/useFetch/useFetch.ts
> +    const res = await fetch(url, options);
`options` is the option part or config part of a fetch request, which consists of method, body, header etc. we can modify as per our requirements. We can even add some utility functions based on our requirement if we want to forward as cookie or get it from session storage, but that depends on the project

2022-09-03 07:39 UTC, psy-tama commented on src/hooks/useFetch/helper.ts
> +      body: JSON.stringify(requestBody)
another way to do is stringify it when using `useFetch` but I think this is more convenient, as this function always stringifies the body which is required by fetch

2022-09-03 07:41 UTC, psy-tama commented on src/hooks/useFetch/useFetch.ts
> +    () => (enabled ? [url, sanitizedOptions] : null),
enabled is the trigger of a particular useFetch hook, if we want to disable the fetch for a certain case we can do that by sending `enabled={false}`, if the first argument of `useSwr` gets a falsy value it does not fetch.

2022-09-03 07:42 UTC, takashi-uix commented on src/hooks/useFetch/useFetch.ts
> +    () => (enabled ? [url, sanitizedOptions] : null),
tested both flows?

2022-09-03 07:43 UTC, takashi-uix commented on src/hooks/useFetch/useFetch.ts
> +    () => (enabled ? [url, sanitizedOptions] : null),
can we also add comments to as what each option does?

2022-09-03 07:43 UTC, takashi-uix commented on src/hooks/useFetch/helper.ts
> +      body: JSON.stringify(requestBody)
Please add a comment on how to add token

2022-09-03 07:44 UTC, psy-tama commented on src/hooks/useFetch/useFetch.ts
> +    () => (enabled ? [url, sanitizedOptions] : null),
will add a detailed document with each use case next.

2022-09-03 15:11 UTC, psy-tama commented
@takashi-uix Added event management wrapper also

2022-09-03 18:02 UTC, takashi-uix approved these changes

2022-09-03 18:02 UTC, merged